name: Doc

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Generate and deploy document
      uses: JamesIves/github-pages-deploy-action@2.0.3
      env:
        BRANCH: gh-pages
        FOLDER: docs
        BUILD_SCRIPT: npm ci && npm run build:doc
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
