name: Tag

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Create tag
      run: |
        tagName="v$(jq '.version' package.json | sed "s/\"//g")"
        if [[ -n $(git ls-remote --tags origin $tagName) ]]; then
          echo "tag $tagName already exists, skip release"
        else
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git tag -a $tagName -m "release by Github Actions"
        fi
    - name: Push to repo
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
